# Generated by Django 3.1.7 on 2021-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_price', models.IntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale time')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Name')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('code', models.IntegerField(unique=True)),
                ('price', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('F', 'Free'), ('S', 'Saled')], default='F', max_length=1)),
            ],
        ),
    ]
